### ISSUE TITLE
where is the chat features ? 🤔🤔

### ISSUE THREAD

**Issue by maxzod** [hatemragab/v_chat_sdk#4]
there is no features list !

**Comment by hatemragab** [comment]
![Screenshot_20211128-181548_Firefox](https://user-images.githubusercontent.com/37384769/143776508-74eadf4a-453a-4fc7-a9c0-abd78803bb68.png)

**Comment by maxzod** [comment]
![-هي-قصة-دورا-الحقيقية-6ze58vdyr7hl9765k3e59mu0vyv3qx9tfhzsphygekz](https://user-images.githubusercontent.com/47630729/143776562-06863248-1a67-4dcc-9695-1781ff6c9efc.jpg)

**Comment by hatemragab** [comment]
Can you check our documention 
https://hatemragab.github.io/VChatSdk-Documentation/docs/intro
